application: xblgamercomp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: static/imgs 

- url: /scripts
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: handler.py


builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest

